version: '3'
services:
  top.api:
    image: docker pull docker.pkg.github.com/antila3567/nest-mongodb/nest-api:develop
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
